<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{B65CA79F-8F76-441E-A587-0BDFE43614B2}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>PIK_GP_Acad</RootNamespace>
    <AssemblyName>PIK_GP_Acad</AssemblyName>
    <TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <UpdateAssemblyVersion>True</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>True</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyVersionSettings>None.None.DayOfYearStamp.Increment</AssemblyVersionSettings>
    <AssemblyFileVersionSettings>None.None.DayOfYearStamp.Increment</AssemblyFileVersionSettings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcadLib, Version=1.0.106.258, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\AcadLib\AcadLib\bin\Release\AcadLib.dll</HintPath>
    </Reference>
    <Reference Include="AcCoreMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Core.20.0.1\lib\45\AcCoreMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcCui, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcCui.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDbMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Model.20.0.1\lib\45\AcDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgdbrep, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Model.20.0.1\lib\45\acdbmgdbrep.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDx, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcDx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMr, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcMr.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcTcMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcTcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcWindows, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows, Version=5.2.10.200, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AutoCAD_PIK_Manager">
      <HintPath>..\..\..\AutoCAD_PIK_Manager\AutoCAD_PIK_Manager\bin\Release\AutoCAD_PIK_Manager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Drawing.Design" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Commands.cs" />
    <Compile Include="Logger.cs" />
    <Compile Include="Model\BlockSection\BlockSectionContours.cs" />
    <Compile Include="Model\BlockSection\DataSection.cs" />
    <Compile Include="Model\BlockSection\Estimate.cs" />
    <Compile Include="Model\BlockSection\EstimateEkb.cs" />
    <Compile Include="Model\BlockSection\EstimateMoscow.cs" />
    <Compile Include="Model\BlockSection\ParserBlockSection.cs" />
    <Compile Include="Model\BlockSection\Section.cs" />
    <Compile Include="Model\BlockSection\SectionService.cs" />
    <Compile Include="Model\BlockSection\SectionType.cs" />
    <Compile Include="Model\BlockSection\SelectSection.cs" />
    <Compile Include="Model\BlockSection\Settings.cs" />
    <Compile Include="Model\BlockSection\TableSecton.cs" />
    <Compile Include="Model\HorizontalElevation\FormHorizontalElevation.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Model\HorizontalElevation\FormHorizontalElevation.Designer.cs">
      <DependentUpon>FormHorizontalElevation.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\HorizontalElevation\Options\FormOptions.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Model\HorizontalElevation\Options\FormOptions.designer.cs">
      <DependentUpon>FormOptions.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\HorizontalElevation\HorizontalElevation.cs" />
    <Compile Include="Model\HorizontalElevation\Options\HorizontalElevationOptions.cs" />
    <Compile Include="Model\InsertBlock.cs" />
    <Compile Include="Model\Isolines\ContextMenuIsoline.cs" />
    <Compile Include="Model\Isolines\FormIsolineOptions.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Model\Isolines\FormIsolineOptions.designer.cs">
      <DependentUpon>FormIsolineOptions.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\Isolines\Isoline.cs" />
    <Compile Include="Model\Isolines\IsolineDrawableOverrule.cs" />
    <Compile Include="Model\Isolines\IsolineOptions..cs" />
    <Compile Include="Model\Isolines\IsolineTransformOverrule.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="AutoCADNetLoad.scr" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model\HorizontalElevation\FormHorizontalElevation.resx">
      <DependentUpon>FormHorizontalElevation.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Model\HorizontalElevation\Options\FormOptions.resx">
      <DependentUpon>FormOptions.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Model\Isolines\FormIsolineOptions.resx">
      <DependentUpon>FormIsolineOptions.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\options.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\GP_HorizontalElevation.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\GP_BlockSectionTable.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\GB_BS.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\GP_BlockParking.PNG" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\GP_Isoline.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>